name: Deploy na VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Configurar SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}

    - name: Deploy na VPS
      env:
        SSH_HOST: root@212.85.13.74
      run: |
        echo "Conectando na VPS..."

        ssh -o StrictHostKeyChecking=no $SSH_HOST << 'EOF'
          set -e

          echo "📦 Criando backup..."
          mkdir -p /root/backups-assistente-radha
          cd /root/projetos
          tar -czf /root/backups-assistente-radha/backup-$(date +%Y-%m-%d-%H-%M-%S).tar.gz assistente-radha

          echo "🧹 Removendo backups antigos..."
          ls -1t /root/backups-assistente-radha | tail -n +4 | xargs -r -I {} rm -f /root/backups-assistente-radha/{}

          echo "🔄 Atualizando projeto..."
          cd /root/projetos/assistente-radha
          git reset --hard
          git pull origin main

          echo "🚀 Reiniciando serviços..."
          systemctl restart radha-backend.service
          systemctl restart radha-frontend.service

          echo "✅ Deploy concluído com sucesso!"
        EOF