name: Deploy Radha Assistente

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}

      - name: Deploy na VPS
        run: |
          ssh -o StrictHostKeyChecking=no root@seu_ip_aqui "
            cd /root/projetos/assistente-radha && \
            git pull origin main && \
            sudo systemctl restart radha-backend.service && \
            sudo systemctl restart radha-frontend.service
          "